import React from 'react';
import { X, AlertTriangle, BookOpen, Scale, FileText } from 'lucide-react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-100 sticky top-0 bg-white z-10">
          <div className="flex items-center gap-2">
            <div className="bg-orange-500 text-white p-1.5 rounded-lg">
              <Scale size={20} />
            </div>
            <h2 className="text-xl font-bold text-gray-900">Terms & Disclaimers</h2>
          </div>
          <button 
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-full transition-colors"
          >
            <X size={24} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 md:p-8 space-y-8">
          
          {/* AI Disclaimer */}
          <section className="bg-orange-50 border border-orange-100 rounded-xl p-6">
            <h3 className="text-lg font-serif font-bold text-gray-900 mb-3 flex items-center gap-2">
              <AlertTriangle size={20} className="text-orange-600" />
              AI & Accuracy Disclaimer
            </h3>
            <p className="text-gray-700 leading-relaxed text-sm">
              <strong>Veritas is an automated system powered by Artificial Intelligence (Google Gemini).</strong> 
              While we strictly filter for trusted news sources, the synthesis, summary, and final verdict are generated by AI. 
              AI models can occasionally "hallucinate" or misinterpret context. 
              <br/><br/>
              Users should <strong>always verify</strong> important information by clicking the direct source links provided. 
              The creator (Aman Singh) and this platform assume no responsibility for errors, omissions, or actions taken based on these results.
            </p>
          </section>

          {/* Educational Purpose */}
          <section>
            <h3 className="text-lg font-serif font-bold text-gray-900 mb-3 flex items-center gap-2">
              <BookOpen size={20} className="text-blue-600" />
              Educational Purpose & Fair Use
            </h3>
            <p className="text-gray-600 leading-relaxed text-sm">
              This application is a <strong>Third Year BSc IT academic project</strong> created by Aman Singh. 
              It is designed strictly for <strong>educational and non-commercial purposes</strong> to demonstrate the capabilities of RAG (Retrieval-Augmented Generation) architectures in combating misinformation.
            </p>
          </section>

          {/* Third Party Content */}
          <section>
            <h3 className="text-lg font-serif font-bold text-gray-900 mb-3 flex items-center gap-2">
              <FileText size={20} className="text-gray-600" />
              Third-Party Content
            </h3>
            <p className="text-gray-600 leading-relaxed text-sm">
              This tool aggregates headlines and snippets from third-party news agencies (e.g., Reuters, AP, BBC) solely for the purpose of verification analysis. 
              <strong>Veritas claims no ownership over the news content displayed.</strong> All rights, titles, and interests in the news articles belong to their respective publishers. Links are provided to drive traffic back to original sources.
            </p>
          </section>

          {/* Liability */}
          <section className="border-t border-gray-100 pt-6">
            <h4 className="font-bold text-gray-900 mb-2">Limitation of Liability</h4>
            <p className="text-xs text-gray-500">
              By using this application, you agree that the creator shall not be held liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use this service. This is a student project provided "as is" without warranty of any kind.
            </p>
          </section>

        </div>
        
        {/* Footer */}
        <div className="p-6 bg-gray-50 border-t border-gray-100 text-center">
            <button 
                onClick={onClose}
                className="px-6 py-2 bg-gray-900 text-white rounded-lg font-medium hover:bg-gray-800 transition-colors"
            >
                I Understand
            </button>
        </div>
      </div>
    </div>
  );
};

export default LegalModal;